name: evepedia

services:
  front:
    image: evepedia/front
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: front
    ports:
      - 5173:5173
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run dev -- --host

  app:
    image: evepedia/app
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: app
    ports:
      - 5678:5678
      - 8000:8000
    volumes:
      - ./:/app
    command: "python -m debugpy --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
      - front

  db:
    image: postgres:16-alpine
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}
      interval: 5s
      timeout: 10s
      retries: 120
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
  db:
