# Generated by Django 5.2.3 on 2025-07-01 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField(verbose_name='Category ID')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='Name')),
                ('published', models.BooleanField(default=True, verbose_name='Published')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField(verbose_name='Group ID')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='Name')),
                ('published', models.BooleanField(default=True, verbose_name='Published')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esi.category')),
            ],
        ),
    ]
