# Generated by Django 5.2.3 on 2025-07-01 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('category_id',)},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ('category__category_id', 'group_id', 'name')},
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.IntegerField(verbose_name='Type ID')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='Name')),
                ('published', models.BooleanField(default=True, verbose_name='Published')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esi.group')),
            ],
            options={
                'ordering': ('group__group_id', 'type_id', 'name'),
            },
        ),
    ]
