# Generated by Django 5.2.3 on 2025-07-01 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esi', '0002_alter_category_options_alter_group_options_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_id', models.IntegerField(verbose_name='Attribute ID')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='Name')),
                ('display_name', models.CharField(blank=True, max_length=128, verbose_name='Display Name')),
                ('default_value', models.IntegerField(default=0, verbose_name='Default Value')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('high_is_good', models.BooleanField(default=False, verbose_name='High is good')),
                ('icon_id', models.IntegerField(blank=True, verbose_name='Icon ID')),
                ('unit_id', models.IntegerField(blank=True, verbose_name='Unit ID')),
                ('published', models.BooleanField(default=True, verbose_name='Published')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TypeAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='Value')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esi.attribute')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esi.type')),
            ],
        ),
    ]
