# Generated by Django 5.2.3 on 2025-07-02 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esi', '0005_alter_attribute_icon_id_alter_attribute_unit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeattribute',
            name='value',
            field=models.FloatField(null=True, verbose_name='Value'),
        ),
    ]
