# Generated by Django 5.2.3 on 2025-07-02 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esi', '0006_alter_typeattribute_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeattribute',
            name='value',
            field=models.CharField(max_length=128, null=True, verbose_name='Value'),
        ),
    ]
