# Generated by Django 5.2.3 on 2025-07-02 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esi', '0007_alter_typeattribute_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='default_value',
            field=models.CharField(default='0', max_length=128, verbose_name='Default Value'),
        ),
    ]
