# Generated by Django 5.2.3 on 2025-07-02 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esi', '0008_alter_attribute_default_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_group_id', models.IntegerField(verbose_name='Market Group ID')),
                ('parent_group_id', models.IntegerField(default=0, verbose_name='Market Group ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='MarketGroupType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esi.marketgroup')),
                ('tyle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esi.type')),
            ],
        ),
    ]
