# Generated by Django 5.2.3 on 2025-07-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esi', '0009_marketgroup_marketgrouptype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketgrouptype',
            old_name='tyle',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='marketgroup',
            name='parent_group_id',
            field=models.IntegerField(default=0, verbose_name='Market Group Parent ID'),
        ),
    ]
